name: Build Docker Image

on:

  workflow_dispatch:
    inputs:
      version:
        description: 'Input Build Version'
        required: true
        default: ''
        type: string

  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            xiaomoy/lsmcd:${{ inputs.version }}
